/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectsProjectIdEnvironmentsRouteImport } from './routes/projects_.$projectId.environments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdEnvironmentsRoute =
  ProjectsProjectIdEnvironmentsRouteImport.update({
    id: '/projects_/$projectId/environments',
    path: '/projects/$projectId/environments',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/projects': typeof ProjectsRoute
  '/projects/$projectId/environments': typeof ProjectsProjectIdEnvironmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/projects': typeof ProjectsRoute
  '/projects/$projectId/environments': typeof ProjectsProjectIdEnvironmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/projects': typeof ProjectsRoute
  '/projects_/$projectId/environments': typeof ProjectsProjectIdEnvironmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/healthz' | '/projects' | '/projects/$projectId/environments'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/healthz' | '/projects' | '/projects/$projectId/environments'
  id:
    | '__root__'
    | '/'
    | '/healthz'
    | '/projects'
    | '/projects_/$projectId/environments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthzRoute: typeof HealthzRoute
  ProjectsRoute: typeof ProjectsRoute
  ProjectsProjectIdEnvironmentsRoute: typeof ProjectsProjectIdEnvironmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId/environments': {
      id: '/projects_/$projectId/environments'
      path: '/projects/$projectId/environments'
      fullPath: '/projects/$projectId/environments'
      preLoaderRoute: typeof ProjectsProjectIdEnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthzRoute: HealthzRoute,
  ProjectsRoute: ProjectsRoute,
  ProjectsProjectIdEnvironmentsRoute: ProjectsProjectIdEnvironmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
